directories:
  output: ./electron-build
  buildResources: build
appId: my-app
win:
  target: nsis
  icon: ./google_meet_icon.ico
nsis:
  oneClick: false
  installerIcon: ./google_meet_icon.ico
  uninstallerIcon: ./google_meet_icon.ico
  uninstallDisplayName: uninstall electron
  license: ./license.md
  allowToChangeInstallationDirectory: true
files: []
electronVersion: 24.1.3
